"""Convert a ShexJESchema to a CanonicalSchema.

Usage::

    from shaclex_py.parser.shexje_parser import parse_shexje
    from shaclex_py.converter.shexje_to_canonical import convert_shexje_to_canonical

    shexje = parse_shexje(json_text)
    canonical = convert_shexje_to_canonical(shexje)
"""
from __future__ import annotations

from typing import Optional

from shaclex_py.schema.canonical import CanonicalProperty, CanonicalSchema, CanonicalShape
from shaclex_py.schema.common import Cardinality, UNBOUNDED
from shaclex_py.schema.shexje import (
    EachOfE,
    NodeConstraintE,
    OneOfE,
    ShapeE,
    ShapeRefE,
    ShexJESchema,
    TripleConstraintE,
)


def _expand_uri(value: str | None, prefixes: dict[str, str]) -> str | None:
    """Expand a prefixed name (e.g. 'xsd:dateTime') to a full IRI using the
    schema prefix map.  Returns the value unchanged if it is already a full IRI,
    is None, or no matching prefix is found.
    """
    if value is None or value.startswith("http") or value.startswith("<"):
        return value
    if ":" in value:
        prefix, local = value.split(":", 1)
        if prefix in prefixes:
            return prefixes[prefix] + local
    return value


# Predicates that encode class membership (rdf:type, wdt:P31, wdt:P279).
# Used to detect value-shape stubs whose single TC encodes a class constraint.
_INSTANCE_PREDICATES: frozenset[str] = frozenset({
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "rdf:type",
    "http://www.wikidata.org/prop/direct/P31",
    "wdt:P31",
    "http://www.wikidata.org/prop/direct/P279",
    "wdt:P279",
})


def _build_shapes_by_id(shexje: ShexJESchema) -> dict[str, ShapeE]:
    """Return a {shape_id: ShapeE} lookup for all ShapeE declarations."""
    return {
        decl.id: decl
        for decl in shexje.shapes
        if isinstance(decl, ShapeE)
    }


def _resolve_shape_ref_to_class(
    ref: str,
    shapes_by_id: dict[str, ShapeE],
    prefixes: dict[str, str],
) -> str | list[str] | None:
    """Resolve a shape reference to a class IRI (or list of IRIs) via value-shape stubs.

    Two patterns are handled:

    1. **Value-shape shorthand** — ShapeE has ``predicate``/``values`` and no
       ``expression``.  The ``values`` list contains the allowed class IRIs.

    2. **Single rdf:type TC** — ShapeE has exactly one TripleConstraint whose
       predicate is an instance-of predicate and whose valueExpr is a
       NodeConstraintE with an IRI value set.  This is the pattern generated by
       ShExJE global-setting LLM output for class-typed IRI predicates.

    Returns the single class IRI string, a list of IRI strings (for OR), or
    ``None`` when the reference cannot be resolved to a class constraint.
    """
    shape = shapes_by_id.get(ref)
    if shape is None or not isinstance(shape, ShapeE):
        return None

    # Pattern 1: shorthand form (predicate/values, no expression)
    if shape.expression is None and shape.values:
        iris = [
            _expand_uri(v, prefixes)
            for v in shape.values
            if isinstance(v, str) and not v.startswith('"')
        ]
        if iris:
            return iris[0] if len(iris) == 1 else iris
        return None

    # Pattern 2: single instanceof TripleConstraint with a value set
    tcs = _collect_tcs(shape.expression)
    if len(tcs) == 1:
        tc = tcs[0]
        expanded_pred = _expand_uri(tc.predicate, prefixes) if tc.predicate else None
        raw_pred = tc.predicate or ""
        is_instance_pred = (
            raw_pred in _INSTANCE_PREDICATES
            or (expanded_pred and expanded_pred in _INSTANCE_PREDICATES)
        )
        if is_instance_pred and isinstance(tc.valueExpr, NodeConstraintE) and tc.valueExpr.values:
            iris = [
                _expand_uri(v, prefixes)
                for v in tc.valueExpr.values
                if isinstance(v, str) and not v.startswith('"')
            ]
            if iris:
                return iris[0] if len(iris) == 1 else iris

    return None


# ---------------------------------------------------------------------------
# Cardinality normalisation
# ---------------------------------------------------------------------------

def _card(min_val, max_val) -> Cardinality:
    """Normalise ShExJE min/max to canonical Cardinality.

    ShExJE conventions: min default 0, max default -1 (unbounded).
    """
    mn = min_val if min_val is not None else 0
    mx = max_val if max_val is not None else UNBOUNDED
    return Cardinality(min=mn, max=mx)


# ---------------------------------------------------------------------------
# Triple-expression tree flattening
# ---------------------------------------------------------------------------

def _collect_tcs(expr) -> list[TripleConstraintE]:
    """Recursively collect all TripleConstraintE objects from an expression tree."""
    if expr is None:
        return []
    if isinstance(expr, TripleConstraintE):
        return [expr]
    if isinstance(expr, (EachOfE, OneOfE)):
        tcs: list[TripleConstraintE] = []
        for child in expr.expressions:
            tcs.extend(_collect_tcs(child))
        return tcs
    # String reference to another expression — ignore
    return []


# ---------------------------------------------------------------------------
# valueExpr extraction helpers
# ---------------------------------------------------------------------------

def _node_kind_str(nk: Optional[str]) -> Optional[str]:
    """Normalise ShExJE nodeKind strings to "IRI", "Literal", etc."""
    if nk is None:
        return None
    mapping = {
        "iri": "IRI",
        "bnode": "BlankNode",
        "nonliteral": "BlankNodeOrIRI",
        "literal": "Literal",
    }
    return mapping.get(nk.lower(), nk)


def _extract_class_iris(values) -> list[str] | None:
    """Return a list of IRI strings from a value set if ALL entries are IRIs.

    Returns None when the set is empty, absent, or contains non-IRI entries
    (literals, stems, etc.) — those are not class constraints.
    """
    if not values:
        return None
    iris: list[str] = []
    for v in values:
        if isinstance(v, str) and not v.startswith('"'):
            iris.append(v)
        else:
            return None  # mixed or literal set — not a pure class constraint
    return iris or None


def _extract_constraint(
    value_expr,
    prefixes: dict[str, str] | None = None,
    shapes_by_id: dict[str, ShapeE] | None = None,
) -> dict:
    """Extract canonical constraint fields from a ShExJE valueExpr.

    Returns a dict with a subset of the keys:
        datatype, classRef, classRefOr, nodeKind, iriStem, pattern, nodeRef

    When *shapes_by_id* is supplied, string-reference ``valueExpr``s are
    resolved through value-shape stubs to ``classRef`` / ``classRefOr`` so
    that exact-match evaluation against SHACL ground truth works correctly.
    """
    pfx = prefixes or {}
    sid = shapes_by_id or {}
    result: dict = {}

    if value_expr is None:
        return result

    # String reference — try to resolve to classRef via value-shape stub.
    if isinstance(value_expr, str):
        resolved = _resolve_shape_ref_to_class(value_expr, sid, pfx)
        if resolved is not None:
            if isinstance(resolved, list):
                result["classRefOr"] = resolved
            else:
                result["classRef"] = resolved
        else:
            result["nodeRef"] = value_expr
        return result

    # ShapeRefE — same resolution logic as above.
    if isinstance(value_expr, ShapeRefE):
        resolved = _resolve_shape_ref_to_class(value_expr.reference, sid, pfx)
        if resolved is not None:
            if isinstance(resolved, list):
                result["classRefOr"] = resolved
            else:
                result["classRef"] = resolved
        else:
            result["nodeRef"] = value_expr.reference
        return result

    # NodeConstraintE
    if isinstance(value_expr, NodeConstraintE):
        if value_expr.datatype:
            result["datatype"] = _expand_uri(value_expr.datatype, pfx)
        if value_expr.nodeKind:
            result["nodeKind"] = _node_kind_str(value_expr.nodeKind)
        if value_expr.pattern:
            result["pattern"] = value_expr.pattern

        # value set — check if it looks like a class constraint (IRI-only list)
        candidate_values = value_expr.values or value_expr.in_values
        class_iris = _extract_class_iris(candidate_values)
        if class_iris:
            expanded = [_expand_uri(iri, pfx) for iri in class_iris]
            if len(expanded) == 1:
                result["classRef"] = expanded[0]
            else:
                result["classRefOr"] = expanded
        return result

    # ShapeE used as a value-shape (value-shape shorthand)
    if isinstance(value_expr, ShapeE):
        if value_expr.values:
            class_iris = _extract_class_iris(value_expr.values)
            if class_iris:
                expanded = [_expand_uri(iri, pfx) for iri in class_iris]
                if len(expanded) == 1:
                    result["classRef"] = expanded[0]
                else:
                    result["classRefOr"] = expanded
        return result

    return result


# ---------------------------------------------------------------------------
# TripleConstraintE → CanonicalProperty
# ---------------------------------------------------------------------------

def _convert_tc(
    tc: TripleConstraintE,
    prefixes: dict[str, str] | None = None,
    shapes_by_id: dict[str, ShapeE] | None = None,
) -> CanonicalProperty | None:
    """Convert one TripleConstraintE to a CanonicalProperty.

    Returns None for inverse triples and non-string predicates (complex paths).
    """
    # Only handle simple forward-predicate triples
    if tc.inverse or not isinstance(tc.predicate, str) or not tc.predicate:
        return None

    cardinality = _card(tc.min, tc.max)
    constraint = _extract_constraint(tc.valueExpr, prefixes=prefixes, shapes_by_id=shapes_by_id)

    return CanonicalProperty(
        path=tc.predicate,
        cardinality=cardinality,
        datatype=constraint.get("datatype"),
        classRef=constraint.get("classRef"),
        classRefOr=constraint.get("classRefOr"),
        nodeKind=constraint.get("nodeKind"),
        pattern=constraint.get("pattern"),
        nodeRef=constraint.get("nodeRef"),
    )


# ---------------------------------------------------------------------------
# ShapeE → CanonicalShape
# ---------------------------------------------------------------------------

def _target_class_str(tc_field) -> Optional[str]:
    """Return the first targetClass as a plain string (handles str | list)."""
    if tc_field is None:
        return None
    if isinstance(tc_field, list):
        return tc_field[0] if tc_field else None
    return tc_field  # already a string


def _convert_shape(
    shape: ShapeE,
    prefixes: dict[str, str] | None = None,
    shapes_by_id: dict[str, ShapeE] | None = None,
) -> CanonicalShape:
    target_class = _target_class_str(shape.targetClass)
    tcs = _collect_tcs(shape.expression)

    properties: list[CanonicalProperty] = []
    seen_paths: set[str] = set()
    for tc in tcs:
        cp = _convert_tc(tc, prefixes=prefixes, shapes_by_id=shapes_by_id)
        if cp is not None and cp.path not in seen_paths:
            seen_paths.add(cp.path)
            properties.append(cp)

    return CanonicalShape(
        name=shape.id,
        targetClass=target_class,
        properties=properties,
    )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def convert_shexje_to_canonical(shexje: ShexJESchema) -> CanonicalSchema:
    """Convert a parsed ShexJESchema to a CanonicalSchema.

    Only ``ShapeE`` declarations with a non-empty expression are converted to
    top-level canonical shapes.  Value-type stub shapes (those with only
    ``predicate``/``values`` and no ``expression``, or with a single instanceof
    TripleConstraint) are skipped as top-level entries but are used *during
    conversion* to resolve string-reference ``valueExpr``s to ``classRef``
    (fixing the ``nodeRef`` vs ``classRef`` mismatch in exact-match evaluation
    against SHACL ground truth).
    """
    prefixes: dict[str, str] = shexje.prefixes or {}
    shapes_by_id = _build_shapes_by_id(shexje)
    shapes: list[CanonicalShape] = []
    for decl in shexje.shapes:
        if isinstance(decl, ShapeE) and decl.expression is not None:
            # Skip stub shapes — those whose entire expression is a single
            # instanceof TC (they encode class constraints, not data shapes).
            tcs = _collect_tcs(decl.expression)
            if len(tcs) == 1:
                expanded_pred = _expand_uri(tcs[0].predicate, prefixes) if tcs[0].predicate else ""
                if expanded_pred in _INSTANCE_PREDICATES or tcs[0].predicate in _INSTANCE_PREDICATES:
                    continue  # value-shape stub — skip as top-level shape
            shapes.append(_convert_shape(decl, prefixes=prefixes, shapes_by_id=shapes_by_id))
    return CanonicalSchema(shapes=shapes)
